version: '3'

services:
  database:
    image: bitnami/postgresql:15.2.0
    ports:
      - "${DB_PORT}:5432"
    environment:
      # source envs/database.env
      POSTGRESQL_DATABASE: "${DB_NAME}"
      POSTGRESQL_USER: "${DB_USER}"
      POSTGRESQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - backend

  backend:
    image: us-central1-docker.pkg.dev/cdc-847-project-1/registry/backend:latest
    restart: always
    command:
      - "server"
    ports:
      - "9000:9000"
    environment:
      DB_HOST: "database"
      DB_PORT: "5432"
    env_file:
      - envs/database.env
      - envs/backend.env
    networks:
      - backend

  frontend:
    image: us-central1-docker.pkg.dev/cdc-847-project-1/registry/frontend:latest
    build:
      context: frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/envs/frontend.env:/app/.env"
    networks:
      - backend

networks:
  backend: