name: Project 1 Frontend CI

on:
  pull_request:
    branches: [ "main" ]
    paths: [ "project_1/frontend/**" ]

defaults:
  run:
    shell: bash
    working-directory: project_1/frontend

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository.
        uses: actions/checkout@v3

      - name: Build
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: csc-847/project-1-frontend
          context: project_1/frontend
          file: project_1/frontend/Dockerfile